apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-staging
nameSuffix: staging
resources:
- ../../bases/application/
- namespace.yaml
replicas
- count: 5
  name: busy-box
