apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox-deployment
  name: busybox-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox-deployment
  template:
    metadata:
      labels:
        app: busybox-deployment
    spec:
      containers:
      - image: busybox
        name: busybox
